package A.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Node_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Node_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "A.structure.Node";
  }
}
