package D.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Root_D_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Root_D_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "D.structure.Root_D";
  }
}
