package D.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Root_D_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    LanguageD.outputRoot(node, this);
  }

  public String getExtension(SNode node) {
    return "d";
  }

  @Override
  public String getFilename(SNode node) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(node, "rootA", true), "name");
  }
}
