package E.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Root_E_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Root_E_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "E.structure.Root_E";
  }
}
