package E.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public abstract class LanguageE {
  public static void outputRoot(SNode rootE, final SNodeTextGen textGen) {
    textGen.getBuffer().append("root in E language");
    textGen.getBuffer().append(textGen.getBuffer().getLineSeparator());
    for (SNode node : ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(rootE, "rootA", true), "nodes", true))) {
      LanguageE.outputNode(node, textGen);
      textGen.getBuffer().append(textGen.getBuffer().getLineSeparator());
    }
  }

  public static void outputNode(SNode nodeA, final SNodeTextGen textGen) {
    textGen.getBuffer().append("<nodeA/>");
  }
}
