package A.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.MappingScriptContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static void mappingScript_CodeBlock_9164034450995229173(final MappingScriptContext _context) {
    ListSequence.fromList(SModelOperations.getRoots(_context.getModel(), "A.structure.Root")).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        SNode rootD = SConceptOperations.createNewNode("D.structure.Root_D", null);
        SNode rootE = SConceptOperations.createNewNode("E.structure.Root_E", null);
        SLinkOperations.setTarget(rootD, "rootA", SNodeOperations.copyNode(it), true);
        SLinkOperations.setTarget(rootE, "rootA", SNodeOperations.copyNode(it), true);
        SModelOperations.addRootNode(_context.getModel(), rootD);
        SModelOperations.addRootNode(_context.getModel(), rootE);
      }
    });
  }
}
